version: '3.1'
services:
  redis:
    image: redis:5
    restart: always
    ports:
        - "6379:6379"
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
