projects:
  cron: "0 0 * * *"
  class: "ProjectFetcherJob"
  queue: projects
  args:
  description: "This job fetches all org projects"

dependencies:
  cron: "5 0 * * *"
  class: "DependenciesFanoutJob"
  queue: dependencies
  args:
  description: "This job spawns jobs to update project dependencies"
